repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        args: [--unsafe]  # For mkdocs.yml
      - id: check-toml
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.16.0
    hooks:
      - id: pretty-format-toml
        args: [--autofix, --indent, "2"]
      - id: pretty-format-yaml
        args: [--autofix, --preserve-quotes, --indent, "2", --offset, "2"]

  - repo: https://github.com/hukkin/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-frontmatter
          - mdformat-gfm
          - mdformat-gfm-alerts
          - mdformat-ruff
          - mdformat-tables
          - mdformat-mkdocs
        args: [--number]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.11
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.6
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.1.0
    hooks:
      - id: mypy
