[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[dependency-groups]
dev = [
  "bump-my-version>=1.3.0",
  "compas_invocations2[mkdocs]>=1.1.2",
  "cwapi3d==33.324.0; python_version>='3.14'",
  "cwapi3d==32.443.10; python_version>='3.12' and python_version<'3.14'",
  "cwapi3d==30.693.0; python_version<'3.12'",
  "invoke>=3.0.3",
  "mkdocs-callouts>=1.16.1",
  "pre-commit>=4.6.0",
  "pytest>=9.0.3",
  "pytest-cov>=7.1.0",
  "griffe-warnings-deprecated>=1.1.1"
]

[project]
authors = [
  {name = "Chen Kasirer", email = "kasirer@arch.ethz.ch"},
  {name = "Matthias Helmreich", email = "helmreich@arch.ethz.ch"},
  {name = "Gonzalo Casas", email = "casas@arch.ethz.ch"},
  {name = "José Miguel Moreno", email = "morenolopez@arch.ethz.ch"}
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Operating System :: Microsoft :: Windows",
  "Topic :: Scientific/Engineering",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14"
]
dependencies = [
  "compas>=2",
  "compas_timber",
  "typing-extensions>=4.15.0"
]
description = "COMPAS package for integrating with cadwork."
dynamic = ["version"]
license = {file = "LICENSE"}
name = "compas_cadwork"
readme = "README.md"
requires-python = ">=3.10"

[project.urls]
Changelog = "https://github.com/gramaziokohler/compas_cadwork/blob/main/CHANGELOG.md"
Homepage = "https://gramaziokohler.github.io/compas_cadwork/"
Issues = "https://github.com/gramaziokohler/compas_cadwork/issues"
Repository = "https://github.com/gramaziokohler/compas_cadwork"

[tool.bumpversion]
commit = true
current_version = "1.0.0"
message = "Bump version to {new_version}"
tag = true

[[tool.bumpversion.files]]
filename = "src/compas_cadwork/__init__.py"
replace = "{new_version}"
search = "{current_version}"

[[tool.bumpversion.files]]
filename = "CHANGELOG.md"
replace = "[{new_version}] {now:%Y-%m-%d}"
search = "Unreleased"

[tool.hatch]
build.targets.wheel.packages = ["src/compas_cadwork"]
version.path = "src/compas_cadwork/__init__.py"

[tool.mypy]
check_untyped_defs = true
explicit_package_bases = true
ignore_missing_imports = false
namespace_packages = true
no_implicit_optional = true
python_version = "3.10"
strict_equality = true
warn_redundant_casts = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
disallow_untyped_calls = false
ignore_missing_imports = true
module = ["compas.*", "compas_timber.*"]

[tool.pytest.ini_options]
addopts = [
  "-ra",
  "--strict-markers",
  "--doctest-modules",
  "--doctest-glob=*.rst",
  "--tb=short",
  "--import-mode=importlib"
]
doctest_optionflags = [
  "NORMALIZE_WHITESPACE",
  "IGNORE_EXCEPTION_DETAIL",
  "ALLOW_UNICODE",
  "ALLOW_BYTES",
  "NUMBER"
]
minversion = "6.0"
python_files = ["test_*.py"]
testpaths = ["tests"]

[tool.ruff]
indent-width = 4
line-length = 120
respect-gitignore = true
show-fixes = true

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = "dynamic"

[tool.ruff.lint]
select = ["A", "B", "E", "ERA", "F", "FA100", "I", "ISC", "NPY", "Q", "RUF", "S110", "T10", "TID", "YTT"]

[tool.ruff.lint.isort]
force-single-line = true
known-first-party = ["compas_cadwork"]
lines-after-imports = 2
order-by-type = true
section-order = [
  "future",
  "standard-library",
  "third-party",
  "first-party",
  "local-folder"
]

[tool.ruff.lint.pycodestyle]
max-doc-length = 120

[tool.ruff.lint.pydocstyle]
convention = "numpy"
