from __future__ import annotations

from abc import abstractmethod
from collections.abc import MutableSet
from functools import cached_property
from typing import TYPE_CHECKING
from typing import Final
from typing import Iterator
from typing import Protocol
from uuid import UUID

import attribute_controller as ac
import cadwork
import element_controller as ec

from compas_cadwork.elements.element import Element
from compas_cadwork.elements.element_type import ElementType


if TYPE_CHECKING:
    from cadwork import ElementId

    from compas_cadwork.elements.factory import AnyElement
else:
    AnyElement = object


class _ElementLike(Protocol):
    id: ElementId

    @property
    def guid(self) -> UUID: ...

    @property
    def group(self) -> str | None: ...

    @group.setter
    def group(self, value: str | None) -> None: ...

    @property
    def type(self) -> ElementType: ...


class _ElementChildren(MutableSet[AnyElement]):
    """Mutable set of the child elements contained in a host element."""

    _parent: Final[_ElementLike]

    def __init__(self, parent: _ElementLike) -> None:
        self._parent = parent

    def __contains__(self, value: object) -> bool:
        if isinstance(value, Element):
            return value.id in self._children_ids()
        return False

    def __iter__(self) -> Iterator[AnyElement]:
        from compas_cadwork.elements.factory import get_element_instance

        for element_id in self._children_ids():
            yield get_element_instance(element_id)

    def __len__(self) -> int:
        return len(self._children_ids())

    @abstractmethod
    def _children_ids(self) -> set[ElementId]:
        """Get element IDs of children.

        Returns
        -------
        set[ElementId]
            Cadwork element IDs.
        """


class _ContainerElementChildren(_ElementChildren):
    """Children set implementation for parent elements that are a container."""

    def add(self, value: AnyElement) -> None:
        if value.id == self._parent.id:
            raise ValueError(f"Cannot add {value!r} as a child of {self._parent!r}")
        children_ids = self._children_ids()
        if value.id not in children_ids:
            children_ids.add(value.id)
            ec.set_container_contents(self._parent.id, list(children_ids))

    def discard(self, value: AnyElement) -> None:
        children_ids = self._children_ids()
        if value.id in children_ids:
            children_ids.remove(value.id)
            ec.set_container_contents(self._parent.id, list(children_ids))

    def _children_ids(self) -> set[ElementId]:
        return set(ec.get_container_content_elements(self._parent.id))


class _GroupElementChildren(_ElementChildren):
    """Children set implementation for parent elements that use groups (e.g., walls)."""

    def add(self, value: AnyElement) -> None:
        if value.id == self._parent.id:
            raise ValueError(f"Cannot add {value!r} as a child of {self._parent!r}")
        group_name = self._parent.group
        if group_name is None:
            group_name = self._default_group_name
            self._parent.group = group_name
        value.group = group_name

    def discard(self, value: AnyElement) -> None:
        child_group = value.group
        if child_group is not None and child_group == self._parent.group:
            value.group = None

    def _children_ids(self) -> set[ElementId]:
        group_name = self._parent.group
        if group_name is None:
            return set()

        # Get all element IDs in the group excluding parent
        children_filter = cadwork.element_filter()
        if ac.get_element_grouping_type() == cadwork.element_grouping_type.subgroup:
            children_filter.set_subgroup(group_name)
        else:
            children_filter.set_group(group_name)
        children_ids = set(ec.filter_elements(ec.get_all_identifiable_element_ids(), children_filter))
        children_ids.remove(self._parent.id)

        # Clear group from parent if it has no children and group was autogenerated by the library
        if not children_ids and group_name == self._default_group_name:
            self._parent.group = None

        return children_ids

    @property
    def _default_group_name(self) -> str:
        return f"G-{self._parent.guid}"


class AggregateMixin:
    """Mixin for elements that support having nested elements."""

    @cached_property
    def children(self: _ElementLike) -> _ElementChildren:
        """Element children."""
        if self.type == ElementType.CONTAINER:
            return _ContainerElementChildren(self)
        return _GroupElementChildren(self)
