name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build:
    if: "!contains(github.event.pull_request.labels.*.name, 'docs-only')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ['3.10']

    steps:
      - uses: compas-dev/compas-actions.build@v4
        with:
          invoke_lint: true
          check_import: false
          use_conda: false
          invoke_test: false
          python: ${{ matrix.python }}
