name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    if: "!contains(github.event.pull_request.labels.*.name, 'docs-only')"
    runs-on: ubuntu-slim
    steps:
      - name: Setup uv
        uses: compas-dev/compas-actions.build@v5.1.0
        with:
          python: 3.12
          management_tool: uv
          invoke_lint: false
          check_import: false
          invoke_test: false

      - name: Run linter
        run: uv run inv lint

      - name: Run tests
        run: uv run inv test

      - name: Build project
        run: uv build
