name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@v8.2.0

      - name: Setup project
        run: uv run inv setup

      - name: Run linter
        run: uv run inv precommit

      - name: Run tests
        run: uv run inv test

      - name: Build project
        run: uv build
