name: docs

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      # Needed to have a system-wide Python binary
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Setup uv
        uses: astral-sh/setup-uv@v8.2.0

      # Needed as the Compas action doesn't support uv
      - name: Install dependencies globally
        run: |
          uv run inv setup
          uv run pre-commit uninstall
          uv export --format requirements.txt -o /tmp/requirements.txt
          uv pip install --system -r /tmp/requirements.txt

      - name: Generate documentation
        uses: compas-dev/compas-actions.docs@v5
        with:
          doc_url: https://gramaziokohler.github.io/compas_cadwork
          github_token: ${{ secrets.GITHUB_TOKEN }}
          python: '3.12'
          use_conda: false
