name: Verify PR checklist

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Check changelog
        uses: Zomzog/changelog-checker@v1.3.0
        with:
          checkNotification: Simple
          fileName: CHANGELOG.md
          noChangelogLabel: 'O: Skip changelog'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  do-not-merge:
    runs-on: ubuntu-slim
    steps:
      - name: Check for label
        run: |
          if [[ "${{ contains(github.event.pull_request.labels.*.name, 'O: Requires rebasing') }}" == "true" ]]; then
            echo "Pull request contains a label that prevents the merge."
            echo "This workflow will now fail."
            exit 1
          fi
          echo "No blocking label found."
          echo "This workflow will now succeed."
