name: verify-pr-checklist

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - main

jobs:
  checklist:
    name: Verify PR checklist
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Check changelog
        uses: Zomzog/changelog-checker@v1.3.0
        with:
          fileName: CHANGELOG.md
          checkNotification: Simple
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
