name: Verify PR checklist

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Check changelog
        uses: Zomzog/changelog-checker@v1.3.0
        with:
          fileName: CHANGELOG.md
          checkNotification: Simple
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  do-not-merge:
    if: "contains(github.event.pull_request.labels.*.name, 'O: Requires rebasing')"
    runs-on: ubuntu-slim
    steps:
      - name: Check for label
        run: |
          echo "Pull request contains a label that prevents the merge."
          echo "This workflow will now fail."
          exit 1
