name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ['3.10']

    steps:
      - uses: compas-dev/compas-actions.build@v3
        with:
          invoke_lint: true
          check_import: false
          use_conda: false
          invoke_test: false
          python: ${{ matrix.python }}

  Publish:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: compas-dev/compas-actions.publish@v2
        with:
          bdist_wheel: true
          sdist: true
          publish_to_pypi: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
